Feature ETP-831: Hand Multi Model and Code Index interaction
etendosoftware/com.etendoerp.copilot.devassistant pull request #17
Opened 2024-11-29 20:20 UTC by JaviBert

2024-12-02 12:23 UTC, valenvivaldi requested changes

2024-12-02 12:23 UTC, valenvivaldi commented on src/com/etendoerp/copilot/devassistant/eventhandler/PathFileHandler.java
>      }
I see that both EHs have a similar logic when checking if the assistant can have Code index.
I would make a function that unifies these logics, then if in the future it is necessary to add a new type, this function is modified.

2024-12-02 14:17 UTC, fran-roig commented on src-db/database/sourcedata/AD_MESSAGE.xml
> +<!--6B6A7DEA19F4449CAED2B85D296D547E-->  <MSGTEXT><![CDATA[Change Assistant type is not available because is a code index type file in the knowldege base file.]]></MSGTEXT>
I would change the message to make it more clear, like:
"The Assistant type cannot be changed because there is an associated code index file in the knowledge base."

2024-12-02 14:18 UTC, fran-roig approved these changes

2024-12-03 18:21 UTC, valenvivaldi commented
Validated

2024-12-03 18:21 UTC, valenvivaldi approved these changes

2024-12-03 18:22 UTC, merged