Feature ETP-839: Add the capability to addd dependencies to a module
etendosoftware/com.etendoerp.copilot.devassistant pull request #18
Opened 2024-12-04 17:22 UTC by JaviBert

2024-12-06 13:35 UTC, fran-roig approved these changes

2024-12-10 13:20 UTC, valenvivaldi commented on src/com/etendoerp/copilot/devassistant/Utils.java
> +    return (Module) criteria.uniqueResult();
The error message must be ad_message

2024-12-10 13:22 UTC, valenvivaldi commented on src/com/etendoerp/copilot/devassistant/webhooks/DependencyAdder.java
> +          OBMessageUtils.getI18NMessage(MISSING_PARAMETER, new String[]{ DEPENDENCY_MODULE_JAVAPACKAGE }));
use messageBD method

2024-12-10 13:22 UTC, valenvivaldi commented on src/com/etendoerp/copilot/devassistant/webhooks/DependencyAdder.java
> +      responseVars.put("message", (String.format("The dependency of the %s was added to the %s.", dependencyModule.getName(), dependentModule.getName())));
ad_message

2024-12-10 13:25 UTC, valenvivaldi commented on src/com/etendoerp/copilot/devassistant/webhooks/JavaPackageRetriever.java
> +
you can use streams to add the "," to separate the strings:

String javapackageList = resultList.stream()
    .map(Module::getJavaPackage)
    .collect(Collectors.joining(", "));

2024-12-10 13:26 UTC, valenvivaldi requested changes
See the comments

2024-12-16 15:01 UTC, JaviBert commented
I need a validation, please @valenvivaldi @fran-roig

2024-12-16 16:47 UTC, fran-roig commented
@JaviBert @valenvivaldi 
Validated. Working as expected.

2024-12-16 16:50 UTC, JaviBert commented
@valenvivaldi I need permission to merge this PR.

2024-12-16 17:37 UTC, fran-roig approved these changes

2024-12-16 17:38 UTC, merged